routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

use App\Role\UserRole;
use Illuminate\Support\Facades\Route;
use Illuminate\Support\Facades\View;
use Stevebauman\Location\Facades\Location;

Auth::routes();
Route::get('/logout', '\App\Http\Controllers\Auth\LoginController@logout');

# site
Route::namespace('Site')->group(function () {
    Route::name('site.')->group(function () {
        Route::get('/', 'SiteController@index')->name('index');
        Route::get('/about', 'SiteController@about')->name('about');
        Route::get('/advertisers', 'SiteController@advertisers')->name('advertisers');
        Route::get('/contacts', 'SiteController@contacts')->name('contacts');
        Route::get('/commerce', 'SiteController@commerce')->name('commerce');
        Route::get('/payment', 'SiteController@payment')->name('payment');
        Route::get('/documents', 'SiteController@view')->name('documents');
        Route::get('/news', 'SiteController@news')->name('news');
        Route::get('/about-project', 'SiteController@aboutProject')->name('about-project');
        Route::get('/tariff', 'SiteController@tariff')->name('tariff');
        Route::get('/tariff-all', 'SiteController@tariffAll')->name('tariff-all');
        Route::post('/report', 'SiteController@lotReport')->name('report');

        // services
        Route::prefix('services')->group(function () {
            Route::name('service.')->group(function () {
                Route::get('/', 'ServiceController@index')->name('page');
                Route::post('/order', 'ServiceController@order')->name('order');
                Route::get('/{service}', 'ServiceController@show')->name('show');
            });
        });

        // questions
        Route::prefix('questions')->group(function () {
            Route::name('question.')->group(function () {
                Route::get('/', 'QuestionController@index')->name('page');
                Route::post('/', 'QuestionController@store')->name('store');
            });
        });

        // consulting
        Route::group(['middleware' => ['auth']], function () {
            Route::prefix('consulting')->group(function () {
                Route::name('consulting.')->group(function () {
                    Route::get('/', 'ConsultingController@index')->name('page');
                    Route::post('/', 'ConsultingController@store')->name('store');
                });
            });
        });

        // catalog
        Route::namespace('Catalog')->group(function () {
            Route::prefix('catalog')->group(function () {
                Route::name('catalog.')->group(function () {
                    Route::get('/', 'CatalogController@index')->name('index');
                    Route::get('/without-category', 'CatalogController@withoutCategory')->name('without');
                    Route::get('/{category}', 'CatalogController@show')->name('category.show');
                    Route::get('/lot/{lot}', 'LotController@show')->name('lot.show');
                });
            });
            Route::prefix('catalog-filter')->group(function () {
                Route::name('catalog-filter.')->group(function () {
                    Route::get('/', 'CatalogController@filterData')->name('index');
                    Route::get('/without-category', 'CatalogController@filterDataWithoutCategory')->name('filterDataWithoutCategory');
                    Route::get('/{category}', 'CatalogController@filterData')->name('filterData');
                });
            });
            Route::prefix('hot-lots')->group(function () {
                Route::name('hot-lots.')->group(function () {
                    Route::get('/', 'HotLotsController@index')->name('index');
                    Route::get('/{category}', 'HotLotsController@show')->name('category.show');
                    Route::get('/lot/{lot}', 'LotController@show')->name('lot.show');
                });
            });
            Route::prefix('hot-lots-filter')->group(function () {
                Route::name('hot-lots-filter.')->group(function () {
                    Route::get('/', 'HotLotsController@filterData')->name('index');
                    Route::get('/{category}', 'HotLotsController@filterData')->name('filterData');
                });
            });
        });

        // Advertising

        Route::prefix('advertising')->group(function() {
            Route::name('advertising.')->group(function() {
                Route::get('/', 'AdvertisingController@index')->name('index');
                Route::get('/show/{banner}', 'AdvertisingController@getEditBanner')->name('edit-banner');
                Route::post('/set/{banner}', 'AdvertisingController@setEditBanner')->name('set-banner');
                Route::post('/', 'AdvertisingController@create')->name('create');
                Route::post('/price', 'AdvertisingController@getPrice')->name('get-price');
                Route::post('/date-check', 'AdvertisingController@dateCheck')->name('date-check');
                Route::get('/get-banners', 'AdvertisingController@getBanners')->name('get-banners');
                Route::get('/new-payment/{payment}', 'AdvertisingController@getNewPayment')->name('new-payment-banner');
            });
        });


        // ajax api
        Route::namespace('Api')->group(function () {
            Route::prefix('api')->group(function () {
                Route::name('api.')->group(function () {
                    Route::post('/site/tariff-get', 'SiteController@tariffGet');

                    Route::post('/location/regions', 'LocationController@regions');
                    Route::get('/location/regions-get', 'LocationController@regionsGet');
                    Route::get('/location/get-session', 'LocationController@getSession');
                    Route::post('/location/set-session', 'LocationController@setSession');

                    Route::prefix('cabinet')->group(function () {
                        Route::name('cabinet.')->group(function () {
                            Route::post('/favorite', 'CabinetController@setFavorite');
                            Route::post('/publish_lot', 'CabinetController@publishLot');
                            Route::get('/user_mailings', 'CabinetController@userMailings');
                            Route::post('/user_mailings', 'CabinetController@updateUserMailing');
                            Route::delete('/user_mailings', 'CabinetController@deleteUserMailing');
                            Route::get('/data_for_mailings', 'CabinetController@dataForMailings');
                            Route::get('/mailing_lots', 'CabinetController@mailingLots');
                        });
                    });

                    Route::prefix('vehicle')->group(function () {
                        Route::name('vehicle.')->group(function () {
                            Route::get('/brands', 'VehicleController@brands');
                            Route::get('/spec-brands', 'VehicleController@specBrands');
                            Route::get('/models', 'VehicleController@models');
                            Route::get('/spec-models', 'VehicleController@specModels');
                        });
                    });

                    Route::prefix('catalog')->group(function () {
                        Route::name('catalog.')->group(function () {
                            Route::post('/trade_organizer_search_list/without-category', 'CatalogController@trade_organizer_search_list_without_category');
                            Route::post('/trade_organizer_search_list/{category}', 'CatalogController@trade_organizer_search_list');
                            Route::post('/debtor_search_list/without-category', 'CatalogController@debtor_search_list_without_category');
                            Route::post('/debtor_search_list/{category}', 'CatalogController@debtor_search_list');
                            Route::post('/trade_organizer_search_list', 'CatalogController@trade_organizer_search_list');
                            Route::post('/debtor_search_list', 'CatalogController@debtor_search_list');
                        });
                    });
                });
            });
        });

    });

    // cabinet
    Route::group(['middleware' => ['auth']], function () {
        Route::prefix('cabinet')->group(function () {
            Route::namespace('Cabinet')->group(function () {
                Route::name('cabinet.')->group(function () {
                    Route::get('/profile', 'ProfileController@index')->name('profile');
                    Route::put('/profile', 'ProfileController@store')->name('change-profile');
                    Route::put('/org-profile', 'ProfileController@store_org_profile')->name('change-org-profile');
                    Route::put('/password', 'ProfileController@store_password')->name('change-password');

                    Route::resource('/notifications', 'NotificationController')->only(['index', 'destroy']);
                    Route::put('/order-evaluation', 'NotificationController@saveOrderEvaluation')->name('order-evaluation');
                    Route::get('/mailings', 'NotificationController@mailings')->name('mailings');
                    Route::get('/favorites', 'FavoriteController@index')->name('favorites');
                    Route::get('/balance', 'PaymentController@index')->name('payments');
                    Route::get('/services', 'ServiceController@index')->name('services');
                    Route::get('/services/{payment}', 'ServiceController@getNewPayment')->name('new-payment-service');

app/Models/Panel/Question.php
<?php

namespace App\Models\Panel;

class Question extends \App\Models\Question
{
    protected $fillable = [
        'author', 'email', 'question', 'answer', 'priority', 'published'
    ];

    public function user()
    {
        return $this->belongsTo(User::class)->withTrashed();
    }
}

app/Models/Question.php
<?php

namespace App\Models;

use App\Events\PanelEvent;
use App\Traits\firePanelModelEvent;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;
use Illuminate\Notifications\Notifiable;
use function Psy\debug;

/**
 * @method static published()
 */
class Question extends Model
{
    use SoftDeletes, Notifiable, firePanelModelEvent;

    protected $fillable = [
        'author', 'email', 'question'
    ];

    protected $casts = [
        'published' => 'boolean',
    ];

    public function attributes()
    {
        return [
            'author' => 'Автор',
            'email' => 'E-mail',
            'question' => 'Вопрос',
            'answer' => 'Ответ',
            'priority' => 'Приоритет',
            'published' => 'Опубликовать на сайте',
        ];
    }

    /**
     * @param \Illuminate\Database\Eloquent\Builder $query
     * @return \Illuminate\Database\Eloquent\Builder
     */
    public function scopePublished($query)
    {
        return $query->where('published', '=', 1);
    }
}

app/Http/Controllers/Panel/QuestionController.php
<?php

namespace App\Http\Controllers\Panel;

use App\Models\Panel\Question;
use App\Role\UserRole;
use App\Traits\PageTableController;

class QuestionController extends Controller
{
    use PageTableController;

    function tableModel()
    {
        return Question::class;
    }

    function tableModelWith()
    {
        return ['user'];
    }

    public function resourceAccess()
    {
        return [
            'list' => UserRole::ROLE_CONTENT,
            'item' => UserRole::ROLE_CONTENT,
            'create' => UserRole::ROLE_CONTENT,
            'update' => UserRole::ROLE_CONTENT,
            'delete' => UserRole::ROLE_CONTENT,
        ];
    }

    public function geCreateValidation()
    {
        return [
            'author' => 'required|string|min:3|max:64',
            'email' => 'required|string|email|max:255',
            'question' => 'required|string|min:30',
            'answer' => 'nullable|string|min:30',
            'priority' => 'nullable|numeric|max:1000000',
            'published' => 'boolean',
        ];
    }

    public function getUpdateValidation()
    {
        return $this->geCreateValidation();
    }

}

app/Http/Controllers/Site/QuestionController.php
<?php

namespace App\Http\Controllers\Site;


use App\Models\Question;
use Illuminate\Http\Request;
use App\Http\Requests\Question as QuestionRequest;
use Illuminate\Support\Facades\Validator;

class QuestionController extends \App\Http\Controllers\Controller
{

    public function index()
    {
        $questions = Question::published()
            ->orderBy('id', 'desc')->paginate(5);
        return view('site/questions', compact('questions'));
    }

    public function store(QuestionRequest $request)
    {
        if ($request->validated()) {
            $question = new Question($request->only(['author', 'email', 'question']));
            $question->saveOrFail();
            $request->session()->flash('question-alert-success', 'Ваш вопрос успешно отправлен');
        }
        return back();
    }

}

resources/views/includes/questions/create.blade.php
<div>

    <form action="{{ route('site.question.store') }}" method="POST" id="questionForm">
        {{ method_field('POST') }}
        @csrf
        @php($user = auth()->user())

        <div class="form-group">
            <label for="inp_author">Имя:</label>
            <input type="text" name="author" value="{{ old('author', $user ? $user->full_name : null) }}"
                   class="form-control @error('author') is-invalid @enderror" id="inp_author"
                   aria-describedby="inp_author_hint">
            @error('author')
            <div class="invalid-feedback">{{ $message }}</div>
            @enderror
        </div>

        <div class="form-group">
            <label for="inp_email">@lang('E-mail'):</label>
            <input type="text" name="email" value="{{ old('email', $user ? $user->email : null) }}"
                   class="form-control @error('email') is-invalid @enderror" id="inp_email"
                   aria-describedby="inp_email_hint">
            @error('email')
            <div class="invalid-feedback">{{ $message }}</div>
            @enderror
        </div>

        <div class="form-group">
            <label for="inp_question">Ваш вопрос:</label>
            <textarea type="text" name="question"
                      class="form-control @error('question') is-invalid @enderror"
                      id="inp_question"
                      rows="5"
                      aria-describedby="inp_question_hint">{{ old('question') }}</textarea>
            @error('question')
            <div class="invalid-feedback">{{ $message }}</div>
            @enderror
        </div>

        <div class="mt-4 mb-2">
            <small>
                <span class="text-danger">*</span> Нажимая на кнопку “Отправить вопрос”, Вы соглашаетесь 
                <a href="{{ route('site.documents', ['tab' => 'policy']) }}" target="_blank"> с положением по обработке персональных данных</a>
            </small>
        </div>
        <button type="submit" class="btn btn-primary">Отправить вопрос</button>
    </form>
</div>

resources/views/includes/questions/item.blade.php
<div class="question-item mb-4">

    <div class="rounded shadow p-4">
        <div class="float-right">
            <div class="question-item-btn">
                <svg width="31" height="32" viewBox="0 0 31 32" fill="none" xmlns="http://www.w3.org/2000/svg">
                    <circle cx="15.5" cy="15.7727" r="14.75" stroke-width="1.5"/>
                    <g>
                        <line x1="15.75" y1="9.02271" x2="15.75" y2="22.5227" stroke-width="1.5"
                              stroke-linecap="round"/>
                        <line x1="8.75" y1="15.5227" x2="22.25" y2="15.5227" stroke-width="1.5" stroke-linecap="round"/>
                    </g>
                </svg>
            </div>
        </div>
        <div class="px-3">
            <div class="h3">{{ $question->question }}</div>
            <small class="text-grey">{{ $question->created_at }} от {{ $question->author }}</small>
        </div>
    </div>
    <div class="question-item-answer-container">
        <div class="rounded p-4 mt-3 question-item-answer">
            <div class="px-3">
                <h5 class="card-title">@lang('Answer')</h5>
                {{ $question->answer }}
            </div>
        </div>
    </div>

</div>