routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

use App\Role\UserRole;
use Illuminate\Support\Facades\Route;
use Illuminate\Support\Facades\View;
use Stevebauman\Location\Facades\Location;

Auth::routes();
Route::get('/logout', '\App\Http\Controllers\Auth\LoginController@logout');

# site
Route::namespace('Site')->group(function () {
    Route::name('site.')->group(function () {
        Route::get('/', 'SiteController@index')->name('index');
        Route::get('/about', 'SiteController@about')->name('about');
        Route::get('/advertisers', 'SiteController@advertisers')->name('advertisers');
        Route::get('/contacts', 'SiteController@contacts')->name('contacts');
        Route::get('/commerce', 'SiteController@commerce')->name('commerce');
        Route::get('/payment', 'SiteController@payment')->name('payment');
        Route::get('/documents', 'SiteController@view')->name('documents');
        Route::get('/news', 'SiteController@news')->name('news');
        Route::get('/about-project', 'SiteController@aboutProject')->name('about-project');
        Route::get('/tariff', 'SiteController@tariff')->name('tariff');
        Route::get('/tariff-all', 'SiteController@tariffAll')->name('tariff-all');
        Route::post('/report', 'SiteController@lotReport')->name('report');

        // services
        Route::prefix('services')->group(function () {
            Route::name('service.')->group(function () {
                Route::get('/', 'ServiceController@index')->name('page');
                Route::post('/order', 'ServiceController@order')->name('order');
                Route::get('/{service}', 'ServiceController@show')->name('show');
            });
        });

        // questions
        Route::prefix('questions')->group(function () {
            Route::name('question.')->group(function () {
                Route::get('/', 'QuestionController@index')->name('page');
                Route::post('/', 'QuestionController@store')->name('store');
            });
        });

        // consulting
        Route::group(['middleware' => ['auth']], function () {
            Route::prefix('consulting')->group(function () {
                Route::name('consulting.')->group(function () {
                    Route::get('/', 'ConsultingController@index')->name('page');
                    Route::post('/', 'ConsultingController@store')->name('store');
                });
            });
        });

        // catalog
        Route::namespace('Catalog')->group(function () {
            Route::prefix('catalog')->group(function () {
                Route::name('catalog.')->group(function () {
                    Route::get('/', 'CatalogController@index')->name('index');
                    Route::get('/without-category', 'CatalogController@withoutCategory')->name('without');
                    Route::get('/{category}', 'CatalogController@show')->name('category.show');
                    Route::get('/lot/{lot}', 'LotController@show')->name('lot.show');
                });
            });
            Route::prefix('catalog-filter')->group(function () {
                Route::name('catalog-filter.')->group(function () {
                    Route::get('/', 'CatalogController@filterData')->name('index');
                    Route::get('/without-category', 'CatalogController@filterDataWithoutCategory')->name('filterDataWithoutCategory');
                    Route::get('/{category}', 'CatalogController@filterData')->name('filterData');
                });
            });
            Route::prefix('hot-lots')->group(function () {
                Route::name('hot-lots.')->group(function () {
                    Route::get('/', 'HotLotsController@index')->name('index');
                    Route::get('/{category}', 'HotLotsController@show')->name('category.show');
                    Route::get('/lot/{lot}', 'LotController@show')->name('lot.show');
                });
            });
            Route::prefix('hot-lots-filter')->group(function () {
                Route::name('hot-lots-filter.')->group(function () {
                    Route::get('/', 'HotLotsController@filterData')->name('index');
                    Route::get('/{category}', 'HotLotsController@filterData')->name('filterData');
                });
            });
        });

        // Advertising

        Route::prefix('advertising')->group(function() {
            Route::name('advertising.')->group(function() {
                Route::get('/', 'AdvertisingController@index')->name('index');
                Route::get('/show/{banner}', 'AdvertisingController@getEditBanner')->name('edit-banner');
                Route::post('/set/{banner}', 'AdvertisingController@setEditBanner')->name('set-banner');
                Route::post('/', 'AdvertisingController@create')->name('create');
                Route::post('/price', 'AdvertisingController@getPrice')->name('get-price');
                Route::post('/date-check', 'AdvertisingController@dateCheck')->name('date-check');
                Route::get('/get-banners', 'AdvertisingController@getBanners')->name('get-banners');
                Route::get('/new-payment/{payment}', 'AdvertisingController@getNewPayment')->name('new-payment-banner');
            });
        });


        // ajax api
        Route::namespace('Api')->group(function () {
            Route::prefix('api')->group(function () {
                Route::name('api.')->group(function () {
                    Route::post('/site/tariff-get', 'SiteController@tariffGet');

                    Route::post('/location/regions', 'LocationController@regions');
                    Route::get('/location/regions-get', 'LocationController@regionsGet');
                    Route::get('/location/get-session', 'LocationController@getSession');
                    Route::post('/location/set-session', 'LocationController@setSession');

                    Route::prefix('cabinet')->group(function () {
                        Route::name('cabinet.')->group(function () {
                            Route::post('/favorite', 'CabinetController@setFavorite');
                            Route::post('/publish_lot', 'CabinetController@publishLot');
                            Route::get('/user_mailings', 'CabinetController@userMailings');
                            Route::post('/user_mailings', 'CabinetController@updateUserMailing');
                            Route::delete('/user_mailings', 'CabinetController@deleteUserMailing');
                            Route::get('/data_for_mailings', 'CabinetController@dataForMailings');
                            Route::get('/mailing_lots', 'CabinetController@mailingLots');
                        });
                    });

                    Route::prefix('vehicle')->group(function () {
                        Route::name('vehicle.')->group(function () {
                            Route::get('/brands', 'VehicleController@brands');
                            Route::get('/spec-brands', 'VehicleController@specBrands');
                            Route::get('/models', 'VehicleController@models');
                            Route::get('/spec-models', 'VehicleController@specModels');
                        });
                    });

                    Route::prefix('catalog')->group(function () {
                        Route::name('catalog.')->group(function () {
                            Route::post('/trade_organizer_search_list/without-category', 'CatalogController@trade_organizer_search_list_without_category');
                            Route::post('/trade_organizer_search_list/{category}', 'CatalogController@trade_organizer_search_list');
                            Route::post('/debtor_search_list/without-category', 'CatalogController@debtor_search_list_without_category');
                            Route::post('/debtor_search_list/{category}', 'CatalogController@debtor_search_list');
                            Route::post('/trade_organizer_search_list', 'CatalogController@trade_organizer_search_list');
                            Route::post('/debtor_search_list', 'CatalogController@debtor_search_list');
                        });
                    });
                });
            });
        });

    });

    // cabinet
    Route::group(['middleware' => ['auth']], function () {
        Route::prefix('cabinet')->group(function () {
            Route::namespace('Cabinet')->group(function () {
                Route::name('cabinet.')->group(function () {
                    Route::get('/profile', 'ProfileController@index')->name('profile');
                    Route::put('/profile', 'ProfileController@store')->name('change-profile');
                    Route::put('/org-profile', 'ProfileController@store_org_profile')->name('change-org-profile');
                    Route::put('/password', 'ProfileController@store_password')->name('change-password');

                    Route::resource('/notifications', 'NotificationController')->only(['index', 'destroy']);
                    Route::put('/order-evaluation', 'NotificationController@saveOrderEvaluation')->name('order-evaluation');
                    Route::get('/mailings', 'NotificationController@mailings')->name('mailings');
                    Route::get('/favorites', 'FavoriteController@index')->name('favorites');
                    Route::get('/balance', 'PaymentController@index')->name('payments');
                    Route::get('/services', 'ServiceController@index')->name('services');
                    Route::get('/services/{payment}', 'ServiceController@getNewPayment')->name('new-payment-service');

resources/views/includes/alert.blade.php
<div class="flash-message">
    @foreach (['danger', 'warning', 'success', 'info'] as $msg)
        @if(Session::has('alert-' . $msg))
            <p class="alert alert-{{ $msg }}">
                {{ Session::get('alert-' . $msg) }}
                <a href="#" class="close" data-dismiss="alert" aria-label="close">&times;</a>
            </p>
        @endif
    @endforeach
</div>

resources/views/includes/header.blade.php
<div class="container">
    <div class="mt-4 mb-2 mb-sm-4">
        <div class="row">
            <div class="col-md-4 col-lg-4 col-12 pr-md-0 pr-lg-4 d-none d-md-block">
                <a href="/" class="">
                    <img src="{{ asset('/img/logo.svg') }}" alt="БАИДС" class="logo w-100 d-none d-lg-inline"/>
                    <img src="{{ asset('/img/logo-sm.svg') }}" alt="БАИДС" class="logo d-lg-none logo-sm"/>
                </a>
            </div>
            <div class="flex-grow-0">
                <button
                    type="button"
                    class="btn btn-lg btn-light shadow rounded bg-white ml-3"
                    onclick="javascript:$('.header-categories').toggleClass('open')"
                >
                    <svg class="category-svg" width="16" height="16" viewBox="0 0 16 16" fill="none" xmlns="http://www.w3.org/2000/svg">
                        <path d="M0.5 3.5H9.5" stroke="#39475F" stroke-linecap="round"/>
                        <path d="M0.5 8.5H13" stroke="#39475F" stroke-linecap="round"/>
                        <path d="M0.5 13.5H15.5" stroke="#39475F" stroke-linecap="round"/>
                    </svg>
                    <span class="d-none d-lg-inline">Категории лотов</span>
                </button>
            </div>
            <search-form
                placeholder = "@lang('Search for lots')"
                action = "{{ $search_url ?? route('site.catalog.index') }}"
                input_str = "{{ request()->get('q') }}"
                synonyms_str = "{{ $synonyms ?? '' }}"
            >
            </search-form>
        </div>
        <div class="row d-none d-sm-block">
            <div class="offset-md-4 col-md-8 col-12 clearfix">

                <div class="float-right">
                    <a href="{{ route('site.catalog.index') }}">
                        <span class="pr-2 p-2">Расширенный поиск</span>
                        <img src="{{ asset('img/icons/16px/config_blue.svg') }}" alt="filter">
                    </a>
                </div>

            </div>
        </div>
    </div>
</div>

<div class="header-categories">
    @php
        $categories = \App\Models\TradeLotCategory::getAllCategories()->sortBy('parent_id');
    @endphp
    <div class="container">
        <div class="row">
            <div class="col-12 col-sm-3 pr-0">
                @php($categories->push((object)['id'=>null, "url" => route('site.catalog.without'), "title" => "Прочее", 'image_url'=>null, 'children'=>[]]))
                @foreach($categories as $category)
                    <div class="list-group list-group-cabinet">
                        <a
                            href="{{ $category->url }}"
                            onmouseover="$('#subcategory-{{ $category->id }}').removeClass('d-none').siblings().addClass('d-none')"
                            class="list-group-item list-group-item-action @if($category->url == url()->current()) text-black-50 @endif"
                        >{{ $category->title }}</a>
                    </div>
                @endforeach
            </div>
            <div class="col-sm-9 border-left pl-4 d-none d-sm-block">
                @foreach($categories as $category)
                    <div id="subcategory-{{ $category->id }}" class="subcategory @if(isset($n)) d-none @endif">

                        <img
                            class="header-categories-image-bg"
                            src="{{ $category->image_url ?: '/img/general-cat-noimg.svg' }}"
                            alt="{{ $category->title }}">

                        <div class="row">
                            <div class="col">
                                @php($n = 0)
                                @forelse($category->children as $sub_category)
                                    <div class="list-group list-group-cabinet">
                                        <a
                                            href="{{ $sub_category->url }}"
                                            class="list-group-item list-group-item-action @if($sub_category->url == url()->current()) disabled text-black-50 @endif"
                                        >{{ $sub_category->title }}</a>
                                    </div>
                                    @if(++$n % 6 === 0) </div>
                            <div class="col"> @endif
                                @empty
                                    <div class="p-4">
                                        <span class="text-black-50 font-italic">Нет подкатегорий</span>
                                    </div>
                                @endforelse
                            </div>
                            {{--<div class="col d-flex flex-grow-0" style="min-height: 300px">
                                <div class="d-flex flex-fill align-content-end">
                                    <img
                                        class="d-flex "
                                        src="{{ $category->image_url ?: '/img/general-cat-noimg.svg' }}"
                                        alt="{{ $category->title }}">
                                </div>
                            </div>--}}
                        </div>
                    </div>
                @endforeach
            </div>
        </div>
    </div>
</div>

resources/views/includes/map.blade.php
<section class="row mt-4 pt-3 section-map">
    <g-map :coordinates=@json($map['coordinates'])></g-map>
</section>

resources/views/includes/seo.blade.php
	
@if(!empty($result_seo['title']))
	@section('title', $result_seo['title'])
@elseif(isset($seo_title))
	@section('title', $seo_title)
@endif
@if(!empty($result_seo['description']))
	<meta name='description' content="{{ $result_seo['description'] }}">
@endif
@if(!empty($result_seo['keywords']))
	<meta name="keywords" content="{{ $result_seo['keywords'] }}">
@endif