routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

use App\Role\UserRole;
use Illuminate\Support\Facades\Route;
use Illuminate\Support\Facades\View;
use Stevebauman\Location\Facades\Location;

Auth::routes();
Route::get('/logout', '\App\Http\Controllers\Auth\LoginController@logout');

# site
Route::namespace('Site')->group(function () {
    Route::name('site.')->group(function () {
        Route::get('/', 'SiteController@index')->name('index');
        Route::get('/about', 'SiteController@about')->name('about');
        Route::get('/advertisers', 'SiteController@advertisers')->name('advertisers');
        Route::get('/contacts', 'SiteController@contacts')->name('contacts');
        Route::get('/commerce', 'SiteController@commerce')->name('commerce');
        Route::get('/payment', 'SiteController@payment')->name('payment');
        Route::get('/documents', 'SiteController@view')->name('documents');
        Route::get('/news', 'SiteController@news')->name('news');
        Route::get('/about-project', 'SiteController@aboutProject')->name('about-project');
        Route::get('/tariff', 'SiteController@tariff')->name('tariff');
        Route::get('/tariff-all', 'SiteController@tariffAll')->name('tariff-all');
        Route::post('/report', 'SiteController@lotReport')->name('report');

        // services
        Route::prefix('services')->group(function () {
            Route::name('service.')->group(function () {
                Route::get('/', 'ServiceController@index')->name('page');
                Route::post('/order', 'ServiceController@order')->name('order');
                Route::get('/{service}', 'ServiceController@show')->name('show');
            });
        });

        // questions
        Route::prefix('questions')->group(function () {
            Route::name('question.')->group(function () {
                Route::get('/', 'QuestionController@index')->name('page');
                Route::post('/', 'QuestionController@store')->name('store');
            });
        });

        // consulting
        Route::group(['middleware' => ['auth']], function () {
            Route::prefix('consulting')->group(function () {
                Route::name('consulting.')->group(function () {
                    Route::get('/', 'ConsultingController@index')->name('page');
                    Route::post('/', 'ConsultingController@store')->name('store');
                });
            });
        });

        // catalog
        Route::namespace('Catalog')->group(function () {
            Route::prefix('catalog')->group(function () {
                Route::name('catalog.')->group(function () {
                    Route::get('/', 'CatalogController@index')->name('index');
                    Route::get('/without-category', 'CatalogController@withoutCategory')->name('without');
                    Route::get('/{category}', 'CatalogController@show')->name('category.show');
                    Route::get('/lot/{lot}', 'LotController@show')->name('lot.show');
                });
            });
            Route::prefix('catalog-filter')->group(function () {
                Route::name('catalog-filter.')->group(function () {
                    Route::get('/', 'CatalogController@filterData')->name('index');
                    Route::get('/without-category', 'CatalogController@filterDataWithoutCategory')->name('filterDataWithoutCategory');
                    Route::get('/{category}', 'CatalogController@filterData')->name('filterData');
                });
            });
            Route::prefix('hot-lots')->group(function () {
                Route::name('hot-lots.')->group(function () {
                    Route::get('/', 'HotLotsController@index')->name('index');
                    Route::get('/{category}', 'HotLotsController@show')->name('category.show');
                    Route::get('/lot/{lot}', 'LotController@show')->name('lot.show');
                });
            });
            Route::prefix('hot-lots-filter')->group(function () {
                Route::name('hot-lots-filter.')->group(function () {
                    Route::get('/', 'HotLotsController@filterData')->name('index');
                    Route::get('/{category}', 'HotLotsController@filterData')->name('filterData');
                });
            });
        });

        // Advertising

        Route::prefix('advertising')->group(function() {
            Route::name('advertising.')->group(function() {
                Route::get('/', 'AdvertisingController@index')->name('index');
                Route::get('/show/{banner}', 'AdvertisingController@getEditBanner')->name('edit-banner');
                Route::post('/set/{banner}', 'AdvertisingController@setEditBanner')->name('set-banner');
                Route::post('/', 'AdvertisingController@create')->name('create');
                Route::post('/price', 'AdvertisingController@getPrice')->name('get-price');
                Route::post('/date-check', 'AdvertisingController@dateCheck')->name('date-check');
                Route::get('/get-banners', 'AdvertisingController@getBanners')->name('get-banners');
                Route::get('/new-payment/{payment}', 'AdvertisingController@getNewPayment')->name('new-payment-banner');
            });
        });


        // ajax api
        Route::namespace('Api')->group(function () {
            Route::prefix('api')->group(function () {
                Route::name('api.')->group(function () {
                    Route::post('/site/tariff-get', 'SiteController@tariffGet');

                    Route::post('/location/regions', 'LocationController@regions');
                    Route::get('/location/regions-get', 'LocationController@regionsGet');
                    Route::get('/location/get-session', 'LocationController@getSession');
                    Route::post('/location/set-session', 'LocationController@setSession');

                    Route::prefix('cabinet')->group(function () {
                        Route::name('cabinet.')->group(function () {
                            Route::post('/favorite', 'CabinetController@setFavorite');
                            Route::post('/publish_lot', 'CabinetController@publishLot');
                            Route::get('/user_mailings', 'CabinetController@userMailings');
                            Route::post('/user_mailings', 'CabinetController@updateUserMailing');
                            Route::delete('/user_mailings', 'CabinetController@deleteUserMailing');
                            Route::get('/data_for_mailings', 'CabinetController@dataForMailings');
                            Route::get('/mailing_lots', 'CabinetController@mailingLots');
                        });
                    });

                    Route::prefix('vehicle')->group(function () {
                        Route::name('vehicle.')->group(function () {
                            Route::get('/brands', 'VehicleController@brands');
                            Route::get('/spec-brands', 'VehicleController@specBrands');
                            Route::get('/models', 'VehicleController@models');
                            Route::get('/spec-models', 'VehicleController@specModels');
                        });
                    });

                    Route::prefix('catalog')->group(function () {
                        Route::name('catalog.')->group(function () {
                            Route::post('/trade_organizer_search_list/without-category', 'CatalogController@trade_organizer_search_list_without_category');
                            Route::post('/trade_organizer_search_list/{category}', 'CatalogController@trade_organizer_search_list');
                            Route::post('/debtor_search_list/without-category', 'CatalogController@debtor_search_list_without_category');
                            Route::post('/debtor_search_list/{category}', 'CatalogController@debtor_search_list');
                            Route::post('/trade_organizer_search_list', 'CatalogController@trade_organizer_search_list');
                            Route::post('/debtor_search_list', 'CatalogController@debtor_search_list');
                        });
                    });
                });
            });
        });

    });

    // cabinet
    Route::group(['middleware' => ['auth']], function () {
        Route::prefix('cabinet')->group(function () {
            Route::namespace('Cabinet')->group(function () {
                Route::name('cabinet.')->group(function () {
                    Route::get('/profile', 'ProfileController@index')->name('profile');
                    Route::put('/profile', 'ProfileController@store')->name('change-profile');
                    Route::put('/org-profile', 'ProfileController@store_org_profile')->name('change-org-profile');
                    Route::put('/password', 'ProfileController@store_password')->name('change-password');

                    Route::resource('/notifications', 'NotificationController')->only(['index', 'destroy']);
                    Route::put('/order-evaluation', 'NotificationController@saveOrderEvaluation')->name('order-evaluation');
                    Route::get('/mailings', 'NotificationController@mailings')->name('mailings');
                    Route::get('/favorites', 'FavoriteController@index')->name('favorites');
                    Route::get('/balance', 'PaymentController@index')->name('payments');
                    Route::get('/services', 'ServiceController@index')->name('services');
                    Route::get('/services/{payment}', 'ServiceController@getNewPayment')->name('new-payment-service');

app/Http/Controllers/Site/AdvertisingController.php
<?php

namespace App\Http\Controllers\Site;

use App\Models\Banner;
use App\Models\Order;
use App\Models\Service;
use App\Models\TradeLotCategory;
use Illuminate\Database\Query\Builder;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Lang;
use App\Http\Requests\Advertising;
use App\Models\UserPayment;
use DateTime;

class AdvertisingController extends Controller
{
    protected $edit_element;

    public function index() {
        $categories = TradeLotCategory::onlyPublic()->rootCategories()->get(['title', 'id', 'slug']);
        $services = Service::published()->advertising()->get(['title', 'id', 'system_key'])->toArray();
        $edit_element = $this->edit_element;

        return view('site/advertising', compact('services', 'categories', 'edit_element'));
    }


    public function getPrice(Request $request){
        $post = $request->post();
        $default_price = Service::published()->advertising()->where('id', $post['service_id'])->value('price');
        $price = Banner::getPrice($post['date_start'], $post['date_end'], $default_price);

        return $price;
    }

    public function dateCheck(Request $request){
        $arr = [];

        $banners = Banner::where('variant', $request['variant'])->where('category_id', $request['category'])->get();
        foreach($banners as $banner) {
            $orders = Order::where('id', $banner['order_id'])->get();
            foreach ($orders as $order) {
                $payments = UserPayment::where('id', $order['payment_id'])->get();
                if (!empty($order['service_begin'])) {
                    if ($payments[0]['status'] === 'success') {
                        array_push($arr, [$order['service_begin'], $order['service_end']]);
                    } elseif (date("Y-m-d H:i:m", time()) <= date("Y-m-d H:i:m", strtotime($order['created_at'] . "+1 day")) AND $payments[0]['status'] === "waiting") {
                        array_push($arr, [$order['service_begin'], $order['service_end']]);
                    }
                }
            }
        }

        return json_encode($arr);
    }


    public function create(Advertising $request) {
        $user = Auth::user();
        $post = request()->post();
        $default_price = Service::published()->advertising()->where('id', $post['service_id'])->value('price');
        $price = Banner::getPrice($post['date_start'], $post['date_end'], $default_price);

        $banner = Banner::create($post + ['user_id'=> $user->id]);

        $banner->setImage($request->file("image"));

        $order = Order::create([
            'service_begin' => $post['date_start'],
            'service_end' => $post['date_end'],
            'user_id' => $user->id,
            'service_id' => $post['service_id'],
            'price' => $price
        ]);

        $banner->update(['order_id' => $order->id]);

        $payment = $order->createUnitellerPayment();

        return $payment->createPaymentForm();
    }

    public function getBanners(Request $request){
        $variant = $request->post('variant', 'horizontal');
        $limit = $request->post('limit', 3);
        $service = $request->post('position', 3);
        $category = $request->post('category', 0);
        if($category) {
            $category = explode('|', $category);
            if ($category[1]) {
                $category = $category[1];
            } elseif ($category[0]) {
                $category = $category[0];
            }
        }
        $banners = Banner::allowed()->active()->variant($variant)->category($category)->service($service)
            ->inRandomOrder()->with('image')
            ->whereHas('order', function($query){
                return $query->where('service_begin', '<=', now())
                    ->where('service_end', '>=', now());
            })
            ->limit($limit)->get()
            ->makeHidden(['user_id', 'category_id', 'created_at', 'order_id', 'service_id', 'status', 'status_name', 'updated_at', 'variant_name']);
        return $banners;
    }

    public function getStringDays($count) {
        return $count . " " . Lang::choice('день|дня|дней', $count, [], 'ru');
    }

    public function getUserTable() {
        if($user = Auth::user()) {
            $banners = Banner::byUser($user->id)->with('order.payment', 'category', 'service')->orderByDesc('created_at')->paginate(10);

            return view('site.cabinet.banners', compact('banners'));
        }
    }

    public function getEditBanner(Banner $banner){
        $this->checkUser($banner);

        $this->edit_element = $banner->load('order', 'image')->toArray();
        return $this->index();
    }

    public function setEditBanner(Banner $banner) {
        $this->checkUser($banner);
        $result = [];
        if($banner->isDeny()) {
            $banner->setModerateFields();

            if(request()->post('add_file')) {
                $image = $banner->setImage(request()->file("image"));
                $banner->setModerateStatus();
                $result['image'] = [
                    'name' => $image->name,
                    'url' => $image->url,
                ];
            }

            $banner->save();
            $result['status'] = $banner->status;
        }
        return response()->json($result, 200);

    }

    public function getNewPayment(UserPayment $payment) {
        $payment->url_return_no = request()->post('back_url_no');
        $payment->url_return_ok = request()->post('back_url_ok');
        return $payment->createPaymentForm();
    }

    public function checkUser($banner) {
        $user = Auth::user();
        if($user && $user->id != $banner->user_id) {
            abort(404);
        }
    }
}

app/Http/Controllers/Site/Api/LocationController.php
<?php

namespace App\Http\Controllers\Site\Api;

use App\Http\Requests\CatalogLocation;
use App\Models\TradeLot;
use Fomvasss\Dadata\Facades\DadataSuggest;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Session;
use Symfony\Component\HttpKernel\Exception\BadRequestHttpException;

/**
 * Контроллер каталога
 * Class CatalogController
 * @package App\Http\Controllers\Site
 */
class LocationController extends \App\Http\Controllers\Controller
{
    public function regions()
    {
        if (empty($region = request()->post('region'))) {
            throw new BadRequestHttpException('Bad request');
        }
        $result = TradeLot::select('city_with_type as text')
            ->where('region_with_type', $region)
            ->orderBy('text')
            ->distinct()
            ->get();
        return response()->json($result);
    }

    public function regionsGet()
    {
        if (empty($str = request()->post('str'))) {
            throw new BadRequestHttpException('Bad request');
        }
        try {
            $result = DadataSuggest::suggest("address", ["query" => $str, "count" => 5]);
        } catch (\Exception $err){
            $result = [];
        }
        return response()->json($result);
    }

    public function getSession()
    {
        return response()->json(CatalogLocation::getFromSession());
    }

    public function setSession(CatalogLocation $request)
    {
        $filter = $request->saveToSession();
        return response()->json($filter);
    }
}

app/Http/Controllers/Site/Cabinet/FavoriteController.php
<?php

namespace App\Http\Controllers\Site\Cabinet;


use App\Models\Banner;

class FavoriteController extends \App\Http\Controllers\Controller
{

    public function index()
    {
        $user = auth()->user();
        $lots = $user->favorite_lots()
            ->orderBy('id', 'desc')
            ->with('favorite')->paginate(20);

        return view('site/cabinet/favorites', compact('lots'));
    }

}

resources/views/site/about-project.blade.php
@extends('layouts.site')
@section('content')
<div class="content">
    <div class="row">
        <about-project :sections="{{ json_encode($sections) }}"></about-project>
    </div>
</div>
@endsection

resources/views/site/advertisers.blade.php
@extends('layouts.site')
@section('content')
<div class="content">
    <div class="row">
        <div class="col">
            <div class="h1">Разместим Вашу рекламу</div>
            <p>Уважаемые гости сайта. ООО БАИДС готов предложить Вам услуги, в виде размещения Вашей информации на платформе сайта baids.ru на правах рекламы.</p>
            <p>Заказать услугу Вы можете в верхней панельной строке сайта, во вкладке 
                <a href="{{ url('/advertising')  }}"
                    @auth

                    @else
                    data-redirect="/advertising"
                    data-toggle="modal"
                    data-target="#modalLogin"
                    @endauth>
                    Реклама.
                </a>
            </p>
            <p>Итоговая стоимость услуг определяется после указания параметров заказа.</p>
            <p>Получить более подробную информацию по услуге Вы можете:</p>
            <p>E-mail: <a href="mailto:info@baids.ru" class="text-dark">info@baids.ru</a></p>
            <p>Телефон: <a href="tel:+79612011338" class="text-dark">8 (961) 201 13 38</a></p>
        </div>
    </div>
</div>
@endsection

resources/views/site/advertising.blade.php
@extends('layouts.site')

@section('title', __('Размещение рекламы'))

@section('breadcrumb')
    <nav aria-label="breadcrumb">
        <ol class="breadcrumb">
            <li class="breadcrumb-item"><a href="/">Главная</a></li>
            <li class="breadcrumb-item active"><a href="{{ route('site.advertising.index') }}">Реклама</a></li>
        </ol>
    </nav>
@endsection



    @section('content')

        @if($services)

            @auth
                <advertising
                    :select_categories="{{ $categories->toJson() }}"
                    :services="{{ json_encode($services) }}"
                    :edit_element="{{ json_encode($edit_element) }}"
                ></advertising>
            @else
                @include('includes.auth.login')
            @endauth

        @else

            <h2 class="m-5 text-center">К сожалению данная услуга отключена</h2>

        @endif



    @endsection

resources/views/site/consulting.blade.php
@extends('layouts.site')

@section('title', __('Online consulting'))

@section('content')
    <div class="content">

        <div class="mb-4">
            <h2>@lang('Online consulting')</h2>
            @include('includes.consulting.create')
        </div>

    </div>
@endsection

resources/views/site/element_select.blade.php
@extends('layouts.site')

@section('content')
    <div class="content">

        {{--@if(false)--}}

        <section class="my-5" style="height: 1000px;">
            <h2>Test</h2>
            <div class="row">
                <div class="col">

                    <test-component></test-component>

                </div>
            </div>
        </section>

    </div>
@endsection

resources/views/site/general.blade.php
@extends('layouts.site')

@section('content')
    <div class="content">
        <div class="row mb-4">
            <div class="col-xl-8 col-lg-7">
                <div class="rounded shadow mb-4 overflow-hidden">
                    <div id="carouselExampleIndicators" class="carousel slide" data-ride="carousel">
                        <ol class="carousel-indicators mb-0 mb-sm-2">
                            @foreach($sliders as $slider)
                                <li data-target="#carouselExampleIndicators" data-slide-to="{{ $loop->index }}" {{ $loop->first ? 'class=active' : ''  }}></li>
                            @endforeach
                        </ol>
                        <div class="carousel-inner">
                            @foreach($sliders as $slider)
                                <div class="carousel-item {{ $loop->first ? 'active' : ''  }}" >
                                    <div class="slider-item d-flex" style="{{ $slider->color ? "background-color: $slider->color;" : ''  }}">
                                        <div class="slider-content m-4">
                                            {!! $slider->content !!}
                                        </div>
                                        @if($slider->image)
                                            <img src="{{ $slider->image->url }}" class="d-block slider-img" alt="...">
                                        @endif
                                    </div>

                                </div>
                            @endforeach
                        </div>
                    </div>
                </div>
            </div>
            <div class="col-xl-4 col-lg-5 d-none d-lg-block">
                @auth
                    <div class="rounded shadow p-4 mb-4" style="height: 250px;">
                        <div class="h1 m-0">Привет, {{ auth()->user()->name }}!</div>

                        <ul class="list-unstyled my-4">
                            <li class="mb-1">
                                <img class="mb-1 mr-1" src="{{ asset('img/icons/message.svg') }}">
                                <a href="{{ route('cabinet.notifications.index') }}" class="text-body">
                                    <span>@lang('Messages') ({{ $user_notifications }})</span>
                                </a>
                            </li>
                            <li class="mb-1">
                                <img class="mb-1 mr-1" src="{{ asset('img/icons/16px/portfolio.svg') }}">
                                <a href="{{ route('cabinet.services') }}" class="text-body">
                                    <span>@lang('Services')</span>
                                </a>
                            </li>
                            <li class="mb-1">
                                <img class="mb-1 mr-1" src="{{ asset('img/icons/16px/heart.svg') }}">
                                <a href="{{ route('cabinet.favorites') }}" class="text-body">
                                    <span>@lang('Favorites') ({{ $user_favorites }})</span>
                                </a>
                            </li>
                            @can('create', \App\Models\Trade::class)
                            <li class="mb-1">
                                <img class="mb-1 mr-1" src="{{ asset('img/icons/16px/hummer.svg') }}">
                                <a href="{{ route('cabinet.bidding') }}" class="text-body">
                                    <span>@lang('Bidding')</span>
                                </a>
                            </li>
                            @endcan
                        </ul>

                        <div class="row">
                            <div class="col flex-grow-1 pr-0">
                                <a class="btn btn-sm btn-light bg-white shadow btn-login" href="{{ route('cabinet.profile') }}">
                                    @lang('Go to cabinet')
                                </a>
                            </div>
                            <div class="col flex-grow-0 text-right py-1" style="min-width: auto">
                                <a href="{{ url('/logout') }}"
                                   class="text-nowrap align-items-center">
                                    <span>@lang('Exit')</span>
                                    <svg width="16" height="16" viewBox="0 0 16 16" fill="none"
                                         xmlns="http://www.w3.org/2000/svg">
                                        <path fill-rule="evenodd" clip-rule="evenodd"
                                              d="M3 1.5C2.17157 1.5 1.5 2.17157 1.5 3V13C1.5 13.8284 2.17157 14.5 3 14.5H9.49918C10.3276 14.5 10.9992 13.8284 10.9992 13V11.3913C10.9992 11.1152 10.7753 10.8913 10.4992 10.8913C10.223 10.8913 9.99918 11.1152 9.99918 11.3913V13C9.99918 13.2761 9.77532 13.5 9.49918 13.5H3C2.72386 13.5 2.5 13.2761 2.5 13L2.5 3C2.5 2.72386 2.72386 2.5 3 2.5H9.49918C9.77532 2.5 9.99918 2.72386 9.99918 3V4.6087C9.99918 4.88484 10.223 5.1087 10.4992 5.1087C10.7753 5.1087 10.9992 4.88484 10.9992 4.6087V3C10.9992 2.17157 10.3276 1.5 9.49918 1.5H3ZM12.2741 5.5085C12.0816 5.31055 11.7651 5.30616 11.5671 5.4987C11.3692 5.69124 11.3648 6.00779 11.5573 6.20574L12.8162 7.49997H6.2496C5.97346 7.49997 5.7496 7.72383 5.7496 7.99997C5.7496 8.27612 5.97346 8.49997 6.2496 8.49997H12.8162L11.5573 9.79421C11.3648 9.99216 11.3692 10.3087 11.5671 10.5012C11.7651 10.6938 12.0816 10.6894 12.2741 10.4915L14.3584 8.34859C14.5472 8.15451 14.5472 7.84543 14.3584 7.65135L12.2741 5.5085Z"
                                              fill="#39475F"/>
                                    </svg>
                                </a>
                            </div>
                        </div>

                    </div>
                @else
                    @include('includes.auth.login')
                @endauth
            </div>
        </div>

        @includeWhen(isset($service_banners), 'includes.services.banners')

        @includeWhen(isset($general_categories), 'site.catalog.blocks.categories')

        <h2 class="mb-4">Новые лоты</h2>
        <div class="row">
            <div class="col-lg-9 order-2 order-md-0">
                @if(filled($lots))
                    @each('components.catalog.item', $lots, 'lot')
                    {{--{{ $lots->links() }}--}}
                    <div class="mb-5 mt-n2 mt-lg-0">
                        <a href="{{ route('site.catalog.index') }}" class="btn btn-primary btn-seemore">Смотреть больше</a>
                    </div>
                @else
                    <div class="mb-4" style="min-height: 220px;">
                        По выбранному Вами местоположению нет лотов
                    </div>
                @endif
            </div>
            <div class="d-none d-lg-block  col-lg-3 order-1 order-md-1">
                <get-banners :limit="2" variant="vertical" position="13" classes="mb-4" styles="height: 460px;"></get-banners>
            </div>
        </div>

        @if(isset($hot_lots))
            <h2  class="mb-4">Успей купить</h2>
            <div class="row">
                <div class="col-lg-9 order-2 order-md-0">
                    @if(filled($hot_lots))
                        @each('components.catalog.item', $hot_lots, 'lot')
                        {{--{{ $completed_lots->links() }}--}}
                        <div class="mb-5 mt-n2 mt-lg-0">
                            <a href="{{ route('site.hot-lots.index') }}" class="btn btn-primary btn-seemore">Смотреть больше</a>
                        </div>
                    @endif
                </div>
            </div>
        @endif

        @if(isset($completed_lots))
            <h2  class="mb-4">Завершенные лоты</h2>
            <div class="row">
                <div class="col-lg-9 order-2 order-md-0">
                    @if(filled($completed_lots))
                        @each('components.catalog.item', $completed_lots, 'lot')
                        {{--{{ $completed_lots->links() }}--}}
                    @endif
                </div>
            </div>
        @endif
        <div class="row order-1 order-md-1">
            <get-banners :limit="1" variant="horizontal" position="13" classes="mb-4 col-12"></get-banners>
        </div>
    </div>
@endsection

resources/views/site/news.blade.php
@extends('layouts.site')
@section('content')
<div class="content">
    <div class="row">
        <div class="col">
            <div class="h1">Актуальные новости</div>
            @if($sorted->count())
                @foreach ($sorted as $section)
                <section class="news row rounded shadow p-3 mb-5">
                    <div class="col">
                        <div class="mb-5"><b>Дата публикации: {{ $section->created_at->format('d.m.Y') }}</b></div>
                        <img src="{{ $section->url_image }}" class="img-fluid">
                    </div>
                    <div class="col-9">
                        <p class="h2">{{ $section->title }}</p>
                        <div class="content_block hide">
                            <p class="news-text">{!! nl2br($section->description) !!}</p>
                        </div>
                        <button class="btn btn-primary float-right content_toggle">Читать полностью</button>
                    </div>
                </section>
                @endforeach
            @else
                <h2 class="mt-3">Скоро здесь будут новости</h2>
            @endif
        </div>
    </div>
</div>
@endsection

resources/views/site/page.blade.php
@extends('layouts.site')

@section('content')
    <div class="content">
        <h1>Контакты</h1>
    </div>
@endsection

resources/views/site/service.blade.php
@extends('layouts.site')

@section('title', __('Service').': '.$service->title)

@section('content')
    <div class="content">
        <h1>{{ $service->title }}</h1>
        <p>
            {{ $service->description }}
        </p>
        @if(filled($service->url_image))
            <img src="{{ $service->url_image }}" class="img" alt="{{ $service->title }}">
        @endif

    </div>
@endsection

resources/views/site/tariff-all.blade.php
@extends('layouts.site')
@section('content')
<div class="content">
    <div class="row">
        <tariff-all></tariff-all>
    </div>
</div>
@endsection