routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

use App\Role\UserRole;
use Illuminate\Support\Facades\Route;
use Illuminate\Support\Facades\View;
use Stevebauman\Location\Facades\Location;

Auth::routes();
Route::get('/logout', '\App\Http\Controllers\Auth\LoginController@logout');

# site
Route::namespace('Site')->group(function () {
    Route::name('site.')->group(function () {
        Route::get('/', 'SiteController@index')->name('index');
        Route::get('/about', 'SiteController@about')->name('about');
        Route::get('/advertisers', 'SiteController@advertisers')->name('advertisers');
        Route::get('/contacts', 'SiteController@contacts')->name('contacts');
        Route::get('/commerce', 'SiteController@commerce')->name('commerce');
        Route::get('/payment', 'SiteController@payment')->name('payment');
        Route::get('/documents', 'SiteController@view')->name('documents');
        Route::get('/news', 'SiteController@news')->name('news');
        Route::get('/about-project', 'SiteController@aboutProject')->name('about-project');
        Route::get('/tariff', 'SiteController@tariff')->name('tariff');
        Route::get('/tariff-all', 'SiteController@tariffAll')->name('tariff-all');
        Route::post('/report', 'SiteController@lotReport')->name('report');

        // services
        Route::prefix('services')->group(function () {
            Route::name('service.')->group(function () {
                Route::get('/', 'ServiceController@index')->name('page');
                Route::post('/order', 'ServiceController@order')->name('order');
                Route::get('/{service}', 'ServiceController@show')->name('show');
            });
        });

        // questions
        Route::prefix('questions')->group(function () {
            Route::name('question.')->group(function () {
                Route::get('/', 'QuestionController@index')->name('page');
                Route::post('/', 'QuestionController@store')->name('store');
            });
        });

        // consulting
        Route::group(['middleware' => ['auth']], function () {
            Route::prefix('consulting')->group(function () {
                Route::name('consulting.')->group(function () {
                    Route::get('/', 'ConsultingController@index')->name('page');
                    Route::post('/', 'ConsultingController@store')->name('store');
                });
            });
        });

        // catalog
        Route::namespace('Catalog')->group(function () {
            Route::prefix('catalog')->group(function () {
                Route::name('catalog.')->group(function () {
                    Route::get('/', 'CatalogController@index')->name('index');
                    Route::get('/without-category', 'CatalogController@withoutCategory')->name('without');
                    Route::get('/{category}', 'CatalogController@show')->name('category.show');
                    Route::get('/lot/{lot}', 'LotController@show')->name('lot.show');
                });
            });
            Route::prefix('catalog-filter')->group(function () {
                Route::name('catalog-filter.')->group(function () {
                    Route::get('/', 'CatalogController@filterData')->name('index');
                    Route::get('/without-category', 'CatalogController@filterDataWithoutCategory')->name('filterDataWithoutCategory');
                    Route::get('/{category}', 'CatalogController@filterData')->name('filterData');
                });
            });
            Route::prefix('hot-lots')->group(function () {
                Route::name('hot-lots.')->group(function () {
                    Route::get('/', 'HotLotsController@index')->name('index');
                    Route::get('/{category}', 'HotLotsController@show')->name('category.show');
                    Route::get('/lot/{lot}', 'LotController@show')->name('lot.show');
                });
            });
            Route::prefix('hot-lots-filter')->group(function () {
                Route::name('hot-lots-filter.')->group(function () {
                    Route::get('/', 'HotLotsController@filterData')->name('index');
                    Route::get('/{category}', 'HotLotsController@filterData')->name('filterData');
                });
            });
        });

        // Advertising

        Route::prefix('advertising')->group(function() {
            Route::name('advertising.')->group(function() {
                Route::get('/', 'AdvertisingController@index')->name('index');
                Route::get('/show/{banner}', 'AdvertisingController@getEditBanner')->name('edit-banner');
                Route::post('/set/{banner}', 'AdvertisingController@setEditBanner')->name('set-banner');
                Route::post('/', 'AdvertisingController@create')->name('create');
                Route::post('/price', 'AdvertisingController@getPrice')->name('get-price');
                Route::post('/date-check', 'AdvertisingController@dateCheck')->name('date-check');
                Route::get('/get-banners', 'AdvertisingController@getBanners')->name('get-banners');
                Route::get('/new-payment/{payment}', 'AdvertisingController@getNewPayment')->name('new-payment-banner');
            });
        });


        // ajax api
        Route::namespace('Api')->group(function () {
            Route::prefix('api')->group(function () {
                Route::name('api.')->group(function () {
                    Route::post('/site/tariff-get', 'SiteController@tariffGet');

                    Route::post('/location/regions', 'LocationController@regions');
                    Route::get('/location/regions-get', 'LocationController@regionsGet');
                    Route::get('/location/get-session', 'LocationController@getSession');
                    Route::post('/location/set-session', 'LocationController@setSession');

                    Route::prefix('cabinet')->group(function () {
                        Route::name('cabinet.')->group(function () {
                            Route::post('/favorite', 'CabinetController@setFavorite');
                            Route::post('/publish_lot', 'CabinetController@publishLot');
                            Route::get('/user_mailings', 'CabinetController@userMailings');
                            Route::post('/user_mailings', 'CabinetController@updateUserMailing');
                            Route::delete('/user_mailings', 'CabinetController@deleteUserMailing');
                            Route::get('/data_for_mailings', 'CabinetController@dataForMailings');
                            Route::get('/mailing_lots', 'CabinetController@mailingLots');
                        });
                    });

                    Route::prefix('vehicle')->group(function () {
                        Route::name('vehicle.')->group(function () {
                            Route::get('/brands', 'VehicleController@brands');
                            Route::get('/spec-brands', 'VehicleController@specBrands');
                            Route::get('/models', 'VehicleController@models');
                            Route::get('/spec-models', 'VehicleController@specModels');
                        });
                    });

                    Route::prefix('catalog')->group(function () {
                        Route::name('catalog.')->group(function () {
                            Route::post('/trade_organizer_search_list/without-category', 'CatalogController@trade_organizer_search_list_without_category');
                            Route::post('/trade_organizer_search_list/{category}', 'CatalogController@trade_organizer_search_list');
                            Route::post('/debtor_search_list/without-category', 'CatalogController@debtor_search_list_without_category');
                            Route::post('/debtor_search_list/{category}', 'CatalogController@debtor_search_list');
                            Route::post('/trade_organizer_search_list', 'CatalogController@trade_organizer_search_list');
                            Route::post('/debtor_search_list', 'CatalogController@debtor_search_list');
                        });
                    });
                });
            });
        });

    });

    // cabinet
    Route::group(['middleware' => ['auth']], function () {
        Route::prefix('cabinet')->group(function () {
            Route::namespace('Cabinet')->group(function () {
                Route::name('cabinet.')->group(function () {
                    Route::get('/profile', 'ProfileController@index')->name('profile');
                    Route::put('/profile', 'ProfileController@store')->name('change-profile');
                    Route::put('/org-profile', 'ProfileController@store_org_profile')->name('change-org-profile');
                    Route::put('/password', 'ProfileController@store_password')->name('change-password');

                    Route::resource('/notifications', 'NotificationController')->only(['index', 'destroy']);
                    Route::put('/order-evaluation', 'NotificationController@saveOrderEvaluation')->name('order-evaluation');
                    Route::get('/mailings', 'NotificationController@mailings')->name('mailings');
                    Route::get('/favorites', 'FavoriteController@index')->name('favorites');
                    Route::get('/balance', 'PaymentController@index')->name('payments');
                    Route::get('/services', 'ServiceController@index')->name('services');
                    Route::get('/services/{payment}', 'ServiceController@getNewPayment')->name('new-payment-service');

resources/views/layouts/app.blade.php
<!DOCTYPE html>
<html lang="{{ str_replace('_', '-', app()->getLocale()) }}">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- CSRF Token -->
    <meta name="csrf-token" content="{{ csrf_token() }}">

    <title>{{ config('app.name', 'Laravel') }}</title>

    <!-- Scripts -->
    <script src="{{ asset('js/app.js') }}" defer></script>

    <!-- Fonts -->
    <link rel="dns-prefetch" href="//fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css?family=Nunito" rel="stylesheet">

    <!-- Styles -->
    <link href="{{ asset('css/app.css') }}" rel="stylesheet">
</head>
<body>
    <div id="app">
        <main id="login-form">
            @yield('content')
        </main>
    </div>
</body>
</html>

resources/views/layouts/cabinet.blade.php
<!DOCTYPE html>
<html lang="{{ str_replace('_', '-', app()->getLocale()) }}">
<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- CSRF Token -->
    <meta name="csrf-token" content="{{ csrf_token() }}">

    <title>@yield('title', config('app.name', 'Laravel'))</title>

    <!-- Styles -->
    <link href="{{ asset('css/site.css') }}" rel="stylesheet">
@stack('styles')

<!-- Scripts -->
    <script src="{{ asset('js/site.js') }}" defer></script>
    @stack('scripts')

    <link rel="apple-touch-icon" sizes="180x180" href="/apple-touch-icon.png">
    <link rel="icon" type="image/png" sizes="32x32" href="/favicon-32x32.png">
    <link rel="icon" type="image/png" sizes="16x16" href="/favicon-16x16.png">
    <link rel="manifest" href="/site.webmanifest">
</head>
<body>
<div id="site">
    @include('includes.navbar')
    @section('header')
        @include('includes.header')
    @show
    <div class="container i-min-height-container">
        <nav aria-label="breadcrumb" class="d-none d-sm-block">
            <ol class="breadcrumb">
                <li class="breadcrumb-item"><a href="/">Главная</a></li>
                <li class="breadcrumb-item active" aria-current="page">Личный кабинет</li>
            </ol>
        </nav>
        <div class="content">
            <div class="row navbar-expand-sm">
                <div class="col-12 d-sm-none d-flex mb-3">
                    <a href="" class="mr-auto cabinet-menu-btn" data-toggle="collapse" data-target="#navbarCabinet"
                       aria-controls="navbarCabinet" aria-expanded="false" aria-label="Toggle navigation">
                        <img class="m-1" src="{{ asset('img/back.svg') }}" alt="info" style="height: 16px;">
                    </a>
                    @php $name = request()->get("name", "Личный кабинет"); @endphp
                    <span class="h1 m-0 mr-auto cabinet-header">{{ $name }}</span>
                </div>
                <div class="collapse navbar-collapse col-12 col-sm-3 pr-0" id="navbarCabinet">
                    <div class="list-group list-group-cabinet w-100">
                        <a
                            href="{{ route('cabinet.profile', ["name" => "Профиль"]) }}"
                            class="list-group-item list-group-item-action @if($current_route === 'cabinet.profile') active disabled @endif">
                            <img class="mb-1 mr-1" src="{{ asset('img/icons/16px/user.svg') }}">
                            <span class="d-sm-none d-md-inline">Профиль</span>
                        </a>
                        <a
                            href="{{ route('cabinet.notifications.index', ["name" => "Оповещения"]) }}"
                            class="list-group-item list-group-item-action @if($current_route === 'cabinet.notifications.index') active disabled @endif">
                            <img class="mb-1 mr-1" src="{{ asset('img/icons/16px/mail.svg') }}" alt="icon">
                            <span class="d-sm-none d-md-inline">
                                Оповещения
                                @if($user_notifications) ({{ $user_notifications }}) @endif
                            </span>
                        </a>
                        <a
                            href="{{ route('cabinet.favorites', ["name" => "Избранное"]) }}"
                            class="list-group-item list-group-item-action @if($current_route === 'cabinet.favorites') active disabled @endif">
                            <img class="mb-1 mr-1" src="{{ asset('img/icons/16px/heart.svg') }}">
                            <span class="d-sm-none d-md-inline">
                                Избранное
                                @if($user_favorites) ({{ $user_favorites }}) @endif
                            </span>
                        </a>
                        <a
                            href="{{ route('cabinet.payments', ["name" => "Платежи"]) }}"
                            class="list-group-item list-group-item-action @if($current_route === 'cabinet.payments') active disabled @endif">
                            <img class="mb-1 mr-1" src="{{ asset('img/icons/16px/wallet.svg') }}">
                            <span class="d-sm-none d-md-inline">Платежи</span>
                        </a>
                        <a
                            href="{{ route('cabinet.services', ["name" => "Мои услуги"]) }}"
                            class="list-group-item list-group-item-action @if($current_route === 'cabinet.services') active disabled @endif">
                            <img class="mb-1 mr-2" src="{{ asset('img/icons/16px/portfolio.svg') }}">
                            <span class="d-sm-none d-md-inline">Мои услуги</span>
                        </a>

                        <a
                            href="{{ route('cabinet.banners', ["name" => "Баннеры"]) }}"
                            class="list-group-item list-group-item-action @if($current_route === 'cabinet.banners') active disabled @endif">
                            <img class="mb-1 mr-1" src="{{ asset('img/icons/16px/hummer.svg') }}">
                            <span class="d-sm-none d-md-inline">Баннеры</span>
                        </a>

                        @can('create', \App\Models\Trade::class)
                        <a
                            href="{{ route('cabinet.bidding', ["name" => "Торги"]) }}"
                            class="list-group-item list-group-item-action @if($current_route === 'cabinet.bidding') active disabled @endif">
                            <img class="mb-1 mr-1" src="{{ asset('img/icons/16px/hummer.svg') }}">
                            <span class="d-sm-none d-md-inline">Торги</span>
                        </a>
                        @endcan

                        <a
                            href="{{ route('logout', ["name" => "Выход"]) }}"
                            class="list-group-item list-group-item-action ">
                            <svg width="16" height="16" viewBox="0 0 16 16" fill="none"
                                 xmlns="http://www.w3.org/2000/svg">
                                <path fill-rule="evenodd" clip-rule="evenodd"
                                      d="M3 1.5C2.17157 1.5 1.5 2.17157 1.5 3V13C1.5 13.8284 2.17157 14.5 3 14.5H9.49918C10.3276 14.5 10.9992 13.8284 10.9992 13V11.3913C10.9992 11.1152 10.7753 10.8913 10.4992 10.8913C10.223 10.8913 9.99918 11.1152 9.99918 11.3913V13C9.99918 13.2761 9.77532 13.5 9.49918 13.5H3C2.72386 13.5 2.5 13.2761 2.5 13L2.5 3C2.5 2.72386 2.72386 2.5 3 2.5H9.49918C9.77532 2.5 9.99918 2.72386 9.99918 3V4.6087C9.99918 4.88484 10.223 5.1087 10.4992 5.1087C10.7753 5.1087 10.9992 4.88484 10.9992 4.6087V3C10.9992 2.17157 10.3276 1.5 9.49918 1.5H3ZM12.2741 5.5085C12.0816 5.31055 11.7651 5.30616 11.5671 5.4987C11.3692 5.69124 11.3648 6.00779 11.5573 6.20574L12.8162 7.49997H6.2496C5.97346 7.49997 5.7496 7.72383 5.7496 7.99997C5.7496 8.27612 5.97346 8.49997 6.2496 8.49997H12.8162L11.5573 9.79421C11.3648 9.99216 11.3692 10.3087 11.5671 10.5012C11.7651 10.6938 12.0816 10.6894 12.2741 10.4915L14.3584 8.34859C14.5472 8.15451 14.5472 7.84543 14.3584 7.65135L12.2741 5.5085Z"
                                      fill="#39475F"/>
                            </svg>
                            <span class="d-sm-none d-md-inline">@lang('Exit')</span>
                        </a>
                    </div>
                </div>
                <div class="col-12 col-sm-9 border-left pl-sm-4">
                    @yield('content')
                </div>
            </div>
        </div>
        <div class="row d-none d-sm-block">
            <div class="col">
                <get-banners :limit="1" variant="horizontal" position="15"></get-banners>
            </div>
        </div>
    </div>
    @include('includes.footer')
</div>
</body>
</html>

resources/views/layouts/panel.blade.php
<!DOCTYPE html>
<html lang="{{ str_replace('_', '-', app()->getLocale()) }}">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- CSRF Token -->
    <meta name="csrf-token" content="{{ csrf_token() }}">
    <script> window.token = '{{ csrf_token() }}'; </script>

    <title>{{ config('app.name', 'Laravel') }}</title>

    <!-- Scripts -->
    <script src="{{ asset('js/panel.js') }}" defer></script>

    <!-- Fonts -->
    <link rel="dns-prefetch" href="//fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css?family=Nunito" rel="stylesheet">

    <!-- Styles -->
    <link href="{{ asset('css/panel.css') }}" rel="stylesheet">

    <script>
        window.profile = @json(\Illuminate\Support\Facades\Auth::user());
    </script>
</head>
<body>
<div id="app">
    @yield('content')
</div>
</body>
</html>

resources/views/layouts/site.blade.php
<!DOCTYPE html>
<html lang="{{ str_replace('_', '-', app()->getLocale()) }}">
<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    @include('includes.seo')
    <!-- CSRF Token -->
    <meta name="csrf-token" content="{{ csrf_token() }}">

    <title>@yield('title', config('app.name', 'Laravel'))</title>

    <!-- Styles -->
    <link href="{{ asset('css/site.css') }}" rel="stylesheet">
@stack('styles')

    <!-- Scripts -->
    <script src="https://yastatic.net/es5-shims/0.0.2/es5-shims.min.js"></script>
    <script src="https://yastatic.net/share2/share.js"></script>

    <script src="{{ asset('js/site.js') }}" defer></script>
    @stack('scripts')

    <link rel="apple-touch-icon" sizes="180x180" href="/apple-touch-icon.png">
    <link rel="icon" type="image/png" sizes="32x32" href="/favicon-32x32.png">
    <link rel="icon" type="image/png" sizes="16x16" href="/favicon-16x16.png">
    <link rel="manifest" href="/site.webmanifest">

    <!-- Yandex.Metrika counter --> <script type="text/javascript" > (function(m,e,t,r,i,k,a){m[i]=m[i]||function(){(m[i].a=m[i].a||[]).push(arguments)}; m[i].l=1*new Date();k=e.createElement(t),a=e.getElementsByTagName(t)[0],k.async=1,k.src=r,a.parentNode.insertBefore(k,a)}) (window, document, "script", "https://mc.yandex.ru/metrika/tag.js", "ym"); ym(71644846, "init", { clickmap:true, trackLinks:true, accurateTrackBounce:true, webvisor:true }); </script> <noscript><div><img src="https://mc.yandex.ru/watch/71644846" style="position:absolute; left:-9999px;" alt="" /></div></noscript> <!-- /Yandex.Metrika counter -->
    <!-- Global site tag (gtag.js) - Google Analytics --><script async src="https://www.googletagmanager.com/gtag/js?id=G-5JXDKK01ZL"></script><script>  window.dataLayer = window.dataLayer || [];  function gtag(){dataLayer.push(arguments);}  gtag('js', new Date());  gtag('config', 'G-5JXDKK01ZL');</script>

</head>
<body>
<div id="site">
    @include('includes.navbar')
    @section('header')
        @include('includes.header', ['synonyms' => $synonyms ?? ''])
    @show
    <div class="container i-min-height-container">
        @yield('breadcrumb')
        @yield('content')
    </div>
    @section('footer')
        @include('includes.footer')
    @show
</div>
</body>
</html>